name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build-and-test:
    strategy: 
      matrix:
        go-version: [1.15.x, 1.16.x]
  
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Build
      run: make build
      
    - name: Test
      run: make test
      
    - name: Run Gosec Security Scanner
      uses: securego/gosec@master
      with: 
        args: ./...
      
      
